version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:latest
    container_name: appsmith
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
